### ISSUE TITLE
Error in draw.union.plot - 1:Degree :NA/NaN

### ISSUE THREAD

**Issue by Krasnopeev** [wilkox/unionplot#1]
Hi,
I tried to use your package but for some data sets occur an error like this:
>draw.union.plot(dataset, GroupFactor = "Sample", ColourFactor = "taxa", Pointsize=8)
Determine degree of centre hexagon...
Generate hexagons and trapezoids...
N6, S034, FN2...
Error in 1:Degree : NA/NaN argument
In addition: Warning messages:
1: In sqrt(9 + (12 * (i - 2))) : NaNs produced
2: In sqrt(9 + (12 * (i - 2))) : NaNs produced
3: In sqrt(9 + (12 * (i - 2))) : NaNs produced 

How can I fix that?

here is my input data...
[data_set.txt](https://github.com/wilkox/unionplot/files/2105409/data_set.txt)

**Comment by wilkox** [comment]
Thanks for the bug report @Krasnopeev. Because I haven't looked at this package for a long time, I did  bit of a general clean up and made some quite large backwards-incompatible changes while fixing this bug. The main function is now called `unionplot` and the arguments to `unionplot` now have different names.

If you install the new version with `devtools::install_github('wilkox/unionplot')`, your data should now work as modified below:

``` r
dataset <- readr::read_tsv("https://github.com/wilkox/unionplot/files/2105409/data_set.txt")
#> Warning: Missing column names filled in: 'X1' [1]
#> Parsed with column specification:
#> cols(
#>   X1 = col_integer(),
#>   OTU = col_character(),
#>   taxa = col_character(),
#>   Sample = col_character(),
#>   Count = col_integer()
#> )
unionplot::unionplot(dataset, group = "Sample", colour = "taxa", collapse = 100)
```

![](https://i.imgur.com/s0EuFVc.png)

Please let me know if you run into any other problems 😄

**Comment by Krasnopeev** [comment]
Thanks a lot!! It works great! 😃
